name: Build and Publish LibreTranslate Docker Image w/ models included

# Manually-triggered action to build the latest version (or optionally, if provided, a release tag)
#  of https://github.com/LibreTranslate/LibreTranslate.
# The image includes language models and is published to https://github.com/users/t-lo/packages/container/package/libretranslate.
on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: Optional version tag to build. Defaults to latest main.
        type: string
        required: false
      tag_as_latest:
        description: Also tag image as latest (in addition to tag supplied / computed).
        type: boolean
        default: false

  workflow_call:
    inputs:
      version_tag:
        description: Optional version tag to build. Defaults to latest main.
        type: string
        required: false
      tag_as_latest:
        description: Also tag image as latest (in addition to tag supplied / computed).
        type: boolean
        default: false


jobs:
  build_and_publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Clone upstream
        run: |
          set -x
          git clone https://github.com/LibreTranslate/LibreTranslate

      - name: Optionally Check Out Tag
        if: ${{ inputs.version_tag }}
        # work around https://github.com/actions/runner/issues/665
        shell: bash
        env:
          VERSION_TAG: ${{ inputs.version_tag }}
        run: |
          cd LibreTranslate
          git checkout "$VERSION_TAG"

      - name: Grok image tag
        run: |
          cd LibreTranslate
          git describe --tags | tee SRC_TAG
          echo "ghcr.io/t-lo/libretranslate:$(cat SRC_TAG)-models" | tee IMAGE_TAG
          echo "IMAGE_TAG=$(cat IMAGE_TAG)" >> "$GITHUB_ENV"

      - name: Build image w/ models
        run: |
          cd LibreTranslate
          docker build -f docker/Dockerfile -t "$IMAGE_TAG" --build-arg with_models=true .

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image
        run: |
          docker push "$(cat LibreTranslate/IMAGE_TAG)"

      - name: Optionally Tag Image as Latest
        if: ${{ inputs.tag_as_latest }}
        run: |
          docker tag "$IMAGE_TAG" ghcr.io/t-lo/libretranslate:latest
          docker push ghcr.io/t-lo/libretranslate:latest

      - name: Send an email to report that a new version is available
        env:
          # required to use server in if condition below.
          # See
          # https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow
          smtp_server_is_set: ${{ secrets.SMTP_SERVER }}
        if: ${{ env.smtp_server_is_set != '' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{secrets.SMTP_SERVER}}
          server_port: 465
          username: ${{secrets.SMTP_USER}}
          password: ${{secrets.SMTP_PASSWORD}}
          to: ${{secrets.EMAIL_TO}} # Not today, spammers!
          from: ${{secrets.EMAIL_FROM}} # see "to:"
          subject: New libretranslate release ${{env.IMAGE_TAG}}
          html_body: |
            <html><body>
              <h1>A new LibreTranslate container image w/ models is available</h1>
              <ul>
                <li>Version: ${{env.IMAGE_TAG}}</li>
                <li>Docker pull url:
                    ghcr.io/t-lo/libretranslate:${{env.IMAGE_TAG}}
                </li>
                <li>GHCR link:
                  <a href="https://github.com/t-lo/LibreTranslate/pkgs/container/libretranslate">
                    https://github.com/t-lo/LibreTranslate/pkgs/container/libretranslate
                  </a>
                </li>
              </ul>
            </body></html>
